apiVersion: v2
name: reth-grandine
description: Helm chart for the reth execution client and grandine consensus client.
sources:
  - https://github.com/paradigmxyz/reth
  - https://github.com/status-im/grandine-eth2
type: application
version: "0.1.0"
appVersion: "1.0.3_0.4.1"
maintainers:
  - name: laibe
    url: https://github.com/laibe
